apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
    service: hello
spec:
  selector:
    app: hello
    service: hello
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP